/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const AntImage: typeof import('antd')['Image']
  const AntList: typeof import('antd')['List']
  const AntSwitch: typeof import('antd')['Switch']
  const AntUpload: typeof import('antd')['Upload']
  const BetaSchemaForm: typeof import('@ant-design/pro-components')['BetaSchemaForm']
  const Button: typeof import('antd')['Button']
  const Card: typeof import('antd')['Card']
  const Divider: typeof import('antd')['Divider']
  const Dropdown: typeof import('antd')['Dropdown']
  const Form: typeof import('antd')['Form']
  const Input: typeof import('antd')['Input']
  const Layout: typeof import('antd')['Layout']
  const Link: typeof import('@tanstack/react-router')['Link']
  const Menu: typeof import('antd')['Menu']
  const Modal: typeof import('antd')['Modal']
  const NProgress: typeof import('nprogress')['default']
  const Outlet: typeof import('@tanstack/react-router')['Outlet']
  const Popover: typeof import('antd')['Popover']
  const ProSkeleton: typeof import('@ant-design/pro-components')['ProSkeleton']
  const ProTable: typeof import('@ant-design/pro-components')['ProTable']
  const Progress: typeof import('antd')['Progress']
  const ProgressBar: typeof import('./src/components/ProgressBar')['default']
  const Select: typeof import('antd')['Select']
  const Space: typeof import('antd')['Space']
  const Table: typeof import('antd')['Table']
  const Tag: typeof import('antd')['Tag']
  const Tooltip: typeof import('antd')['Tooltip']
  const Typography: typeof import('antd')['Typography']
  const createFileRoute: typeof import('@tanstack/react-router')['createFileRoute']
  const createRef: typeof import('react')['createRef']
  const dayjs: typeof import('./src/lib/dayjs')['dayjs']
  const forwardRef: typeof import('react')['forwardRef']
  const lazy: typeof import('react')['lazy']
  const memo: typeof import('react')['memo']
  const message: typeof import('antd')['message']
  const sky: typeof import('./src/lib/sky')['default']
  const startTransition: typeof import('react')['startTransition']
  const theme: typeof import('antd')['theme']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useDebugValue: typeof import('react')['useDebugValue']
  const useDeferredValue: typeof import('react')['useDeferredValue']
  const useEffect: typeof import('react')['useEffect']
  const useId: typeof import('react')['useId']
  const useImperativeHandle: typeof import('react')['useImperativeHandle']
  const useInsertionEffect: typeof import('react')['useInsertionEffect']
  const useLayoutEffect: typeof import('react')['useLayoutEffect']
  const useMemo: typeof import('react')['useMemo']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useState: typeof import('react')['useState']
  const useSyncExternalStore: typeof import('react')['useSyncExternalStore']
  const useTransition: typeof import('react')['useTransition']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { ActionType, ProColumns, ProFormColumnsType, ProFormInstance } from '@ant-design/pro-components'
  import('@ant-design/pro-components')
  // @ts-ignore
  export type { Dayjs } from './src/lib/dayjs'
  import('./src/lib/dayjs')
}
